name: sycon_ticketing_app
description: A Ticketing App for SSN Sycon 2022.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  cloud_functions: ^3.2.12
  fl_chart: ^0.50.1
  flutter_riverpod: ^1.0.3
  lottie: ^1.3.0
  mobile_scanner: ^1.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_Regular.ttf
        - asset: assets/fonts/NunitoSans_Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_ExtraBold.ttf
          weight: 800