name: sycon_ticketing_app
description: A Ticketing App for SSN Sycon 2022.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  cloud_functions: ^4.6.4
  fl_chart: ^0.66.1
  flutter_riverpod: ^2.4.9
  lottie: ^3.0.0
  mobile_scanner: ^4.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_Regular.ttf
        - asset: assets/fonts/NunitoSans_Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_ExtraBold.ttf
          weight: 800